version: '3'
services:
  phising-checker:
    build: 
      context: ../
      dockerfile: docker/dev.Dockerfile
    container_name: phising-checker_dev
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    restart: unless-stopped
    env_file:
      - app.env
